import { db, dbPath, ref, update, remove, onValue } from "./firebase.js";
const personId=new URLSearchParams(location.search).get("id");
const peopleRef=ref(db,dbPath("people")),transactionsRef=ref(db,dbPath("transactions"));
let person=null,transactions={};
function formatMoney(n){return Number(n).toLocaleString("en-IN",{minimumFractionDigits:0,maximumFractionDigits:2});}
function escapeHtml(t){const d=document.createElement("div");d.textContent=String(t??"");return d.innerHTML;}
function type(t){return t.type==="credit"||t.type==="taken"?"credit":t.type==="debit"||t.type==="repaid"?"debit":"other";}
function typeLabel(t){return type(t)==="credit"?"Credit":type(t)==="debit"?"Debit":(t.otherType||"Other");}
function total(t){const charges=Array.isArray(t.charges)?t.charges.reduce((s,c)=>s+(Number(c.amount)||0),0):(Number(t.charge)||0);return (Number(t.amount)||0)+charges;}
function fallbackTime(t){if(t.time)return t.time;if(t.createdAt){const d=new Date(t.createdAt);return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`;}return "";}
function sortValue(t){return `${t.date||"0000-00-00"}T${t.time||"00:00"}`;}
window.deleteDetailTransaction=async id=>{if(confirm("Delete this transaction permanently?"))await remove(ref(db,dbPath(`transactions/${id}`)));};
window.editDetailTransaction=async id=>{const t=transactions[id];if(!t)return;const amount=prompt("Amount:",t.amount??"");if(amount===null)return;const value=Number(amount);if(!value||value<=0)return alert("Enter a valid amount");const date=prompt("Date (YYYY-MM-DD):",t.date||"");if(date===null)return;const time=prompt("Time (HH:MM):",fallbackTime(t));if(time===null)return;const purpose=prompt("Purpose:",t.purpose||"");if(purpose===null)return;const comment=prompt("Total comment:",t.description||"");if(comment===null)return;await update(ref(db,dbPath(`transactions/${id}`)),{amount:value,date,time,purpose:purpose.trim(),description:comment.trim()});};
function render(){const title=document.getElementById("personTitle"),c=document.getElementById("detailTransactions");if(!personId||!person){title.textContent="Person not found";c.innerHTML="<p>This person does not exist.</p>";return;}title.textContent=person.name;const list=Object.entries(transactions).filter(([,t])=>t.personId===personId).sort((a,b)=>sortValue(b[1]).localeCompare(sortValue(a[1]))||(b[1].createdAt||0)-(a[1].createdAt||0));let credit=0,debit=0;list.forEach(([,t])=>{if(type(t)==="credit")credit+=total(t);else if(type(t)==="debit")debit+=total(t);});document.getElementById("detailReceived").textContent=`₹${formatMoney(credit)}`;document.getElementById("detailRepaid").textContent=`₹${formatMoney(debit)}`;document.getElementById("detailBalance").textContent=`₹${formatMoney(credit-debit)}`;c.innerHTML="";if(!list.length){c.innerHTML="<p>No transactions for this person.</p>";return;}const wrap=document.createElement("div");wrap.className="ledger-table-wrap";wrap.innerHTML=`<table class="ledger-table"><thead><tr><th>Date</th><th>Time</th><th>Amt</th><th>Cmnt</th><th>Charges</th><th>Cmnt</th><th>Total</th><th>Cmnt</th><th>Purpose</th><th>Type</th><th>Platform</th><th>Actions</th></tr></thead><tbody></tbody></table>`;const tbody=wrap.querySelector("tbody");list.forEach(([id,t])=>{const charges=Array.isArray(t.charges)?t.charges:(Number(t.charge)?[{amount:Number(t.charge),comment:""}]:[]),sum=charges.reduce((s,x)=>s+(Number(x.amount)||0),0),comments=charges.map(x=>x.comment).filter(Boolean).join("; "),tr=document.createElement("tr");tr.innerHTML=`<td>${escapeHtml(t.date||"")}</td><td>${escapeHtml(fallbackTime(t))}</td><td>₹${formatMoney(t.amount)}</td><td>${escapeHtml(t.amountComment||"")}</td><td>₹${formatMoney(sum)}</td><td>${escapeHtml(comments)}</td><td class="${type(t)==="credit"?"taken-text":"repaid-text"}">${type(t)==="credit"?"+":"-"}₹${formatMoney(total(t))}</td><td>${escapeHtml(t.description||"")}</td><td>${escapeHtml(t.purpose||"")}</td><td><span class="type-badge ${type(t)}">${escapeHtml(typeLabel(t))}</span></td><td><span class="platform-badge">${escapeHtml(t.platform||t.method||"Other")}</span></td><td class="action-cell"><button class="table-action edit-action" onclick="editDetailTransaction('${id}')">Edit</button><button class="table-action delete-action" onclick="deleteDetailTransaction('${id}')">Delete</button></td>`;tbody.appendChild(tr);});c.appendChild(wrap);}
document.getElementById("backBtn").addEventListener("click",()=>history.back());
onValue(peopleRef,s=>{person=(s.val()||{})[personId]||null;render();});onValue(transactionsRef,s=>{transactions=s.val()||{};render();});