import { db, ref, remove, onValue } from "./firebase.js";
const personId = new URLSearchParams(location.search).get("id");
const peopleRef = ref(db,"mypayments/people"), transactionsRef = ref(db,"mypayments/transactions");
let person=null, transactions={};
function formatMoney(n){return Number(n).toLocaleString("en-IN",{minimumFractionDigits:0,maximumFractionDigits:2});}
function escapeHtml(t){const d=document.createElement("div");d.textContent=String(t??"");return d.innerHTML;}
function type(t){return t.type==="credit"||t.type==="taken"?"credit":t.type==="debit"||t.type==="repaid"?"debit":"other";}
function typeLabel(t){return type(t)==="credit"?"Credit":type(t)==="debit"?"Debit":(t.otherType||"Other");}
function total(t){const charges=Array.isArray(t.charges)?t.charges.reduce((s,c)=>s+(Number(c.amount)||0),0):(Number(t.charge)||0);return (Number(t.amount)||0)+charges;}
function render(){const title=document.getElementById("personTitle"),c=document.getElementById("detailTransactions");if(!personId||!person){title.textContent="Person not found";c.innerHTML="<p>This person does not exist.</p>";return;}title.textContent=person.name;const list=Object.entries(transactions).filter(([,t])=>t.personId===personId).sort((a,b)=>new Date(b[1].date)-new Date(a[1].date)||(b[1].createdAt||0)-(a[1].createdAt||0));let credit=0,debit=0;list.forEach(([,t])=>{if(type(t)==="credit")credit+=total(t);else if(type(t)==="debit")debit+=total(t);});document.getElementById("detailReceived").textContent=`₹${formatMoney(credit)}`;document.getElementById("detailRepaid").textContent=`₹${formatMoney(debit)}`;document.getElementById("detailBalance").textContent=`₹${formatMoney(credit-debit)}`;c.innerHTML="";if(!list.length){c.innerHTML="<p>No transactions for this person.</p>";return;}const wrap=document.createElement("div");wrap.className="ledger-table-wrap";wrap.innerHTML=`<table class="ledger-table"><thead><tr><th>Amt</th><th>Cmnt</th><th>Charges</th><th>Cmnt</th><th>Total</th><th>Cmnt</th><th>Purpose</th><th>Type</th><th>Platform</th><th></th></tr></thead><tbody></tbody></table>`;const tbody=wrap.querySelector("tbody");list.forEach(([id,t])=>{const charges=Array.isArray(t.charges)?t.charges:(Number(t.charge)?[{amount:Number(t.charge),comment:""}]:[]),sum=charges.reduce((s,x)=>s+(Number(x.amount)||0),0),comments=charges.map(x=>x.comment).filter(Boolean).join("; "),tr=document.createElement("tr");tr.innerHTML=`<td>₹${formatMoney(t.amount)}</td><td>${escapeHtml(t.amountComment||"")}</td><td>₹${formatMoney(sum)}</td><td>${escapeHtml(comments)}</td><td class="${type(t)==="credit"?"taken-text":"repaid-text"}">${type(t)==="credit"?"+":"-"}₹${formatMoney(total(t))}</td><td>${escapeHtml(t.description||"")}</td><td>${escapeHtml(t.purpose||"")}</td><td>${escapeHtml(typeLabel(t))}</td><td>${escapeHtml(t.platform||t.method||"Other")}</td><td><button class="delete-btn" onclick="deleteDetailTransaction('${id}')">Delete</button></td>`;tbody.appendChild(tr);});c.appendChild(wrap);}
window.deleteDetailTransaction=async id=>{if(confirm("Delete this transaction?"))await remove(ref(db,`mypayments/transactions/${id}`));};
document.getElementById("backBtn").addEventListener("click",()=>history.back());
onValue(peopleRef,s=>{person=(s.val()||{})[personId]||null;render();});onValue(transactionsRef,s=>{transactions=s.val()||{};render();});
